import esbuild from "esbuild";
import process from "process";
import { readFile } from "node:fs/promises";
import { builtinModules } from "node:module";

const production = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: "/* Generated by esbuild. Edit files in src/ instead. */",
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [
    {
      name: "sql-js-browser-runtime",
      setup(build) {
        build.onLoad(
          { filter: /sql-asm\.js$/ },
          async ({ path }) => {
            const source = await readFile(path, "utf8");
            const browserOnly = source
              .replace(
                /var aa=!!globalThis\.window,ba=!!globalThis\.WorkerGlobalScope,ca=globalThis\.process\?\.versions\?\.node&&"renderer"!=globalThis\.process\?\.type;/,
                "var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope;",
              )
              .replace(
                /if\(ca\)\{var fs=require\("node:fs"\);[\s\S]*?xa=\(a,b\)=>\{process\.exitCode=a;throw b;\}\}else if\(aa\|\|ba\)/,
                "if(aa||ba)",
              )
              .replace(
                /\$a=\(\)=>\{if\(ca\)\{var a=require\("node:crypto"\);return b=>a\.randomFillSync\(b\)\}return b=>crypto\.getRandomValues\(b\)\}/,
                "$a=()=>b=>crypto.getRandomValues(b)",
              );
            if (
              browserOnly === source ||
              /require\("node:(?:fs|crypto)"\)/.test(browserOnly)
            ) {
              throw new Error(
                "Could not lock sql.js to its browser runtime",
              );
            }
            return {
              contents: browserOnly,
              loader: "js",
            };
          },
        );
      },
    },
  ],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
    ...builtinModules.map((moduleName) => `node:${moduleName}`),
  ],
  format: "cjs",
  target: "es2021",
  define: {
    "globalThis.process": "undefined",
  },
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
